### ISSUE TITLE
Release is tagged v6.2.22, but title says 6.2.18

### ISSUE THREAD

**Issue by imsedgar** [praat/praat#2208] opened 2022-09-02 20:45 UTC
praat version 6.2.18 is released with tag v6.2.22:
https://github.com/praat/praat/releases/tag/v6.2.22

**Comment by alerque** [comment] 2022-09-02 21:59
Duplicate of #2207.

**Comment by imsedgar** [comment] 2022-09-02 22:11
@alerque Yes, #2007 describes the same problem. But sorry, I didn't see your issue, your title is too less descriptive.

**Comment by PaulBoersma** [comment] 2022-09-11 16:48
OK, I sort of repaired this now.

**Closed by PaulBoersma** 2022-09-11 16:48 UTC
