### ISSUE TITLE
Linux version no longer usable

### ISSUE THREAD

**Issue by Trevortds** [praat/praat#161] opened 2016-01-19 16:49 UTC
It seems like this issue was fixed back in 2011, but as of the latest release (and it's been a while since I've installed praat, so I don't know how far back it goes), the tab shortcut is broken on linux. There is no way to play sound except with view>play...>(manually type in start and endpoint). Praat is unusable in this state, please rollback or otherwise fix as soon as possible.

**Comment by drammock** [comment] 2016-01-19 20:58
confirmed that tab key doesn't trigger playback in Sound editor windows on praat 6.0.11 on Xubuntu 14.04 (both 64-bit).  I tried messing with the sound playing preferences but this didn't change the behavior (tried both PulseAudio and ALSA via PortAudio, and both asynchronous and interruptible).  @Trevortds surely you can still play back by clicking on the gray rectangles (e.g. "visible part" or "total duration") below the waveform or spectrogram?  Or is it really only the menu command that works?

**Comment by Trevortds** [comment] 2016-01-19 23:46
To be perfectly honest, I did not know that the grey rectangles across 
the bottom of the display were buttons. They do work, it is only the 
keyboard shortcut that does not.

To me it is pretty clearly not a problem related to PulseAudio or ALSA, 
but something internal to Praat. Even without that workaround, I could 
get it to work before by typing in a start and end point in the menu 
command. It's worth noting that the "play" menu command (the one that 
binds to tab) also does not work when clicked. Only the menu command 
marked "play..." that opens a dialog.

**Comment by drammock** [comment] 2016-01-19 23:58
Thanks for clarifying. I'm seeing the same thing here: `Play window (Shift+Tab)` and `Play or stop (Tab)` are both giving no response when selected from the `View` menu or when attempting to invoke from their keyboard shortcuts.  Given that the menu commands fail too, I don't think it's an issue of the OS swallowing the keystrokes before they are passed on to praat (which would have been my next guess: I've seen it happen with other apps, especially the `Super` key).

re: sound playing preferences: I wasn't expecting ALSA/Pulse to make a difference either, but I'm less certain about the asynchronicity setting.

**Comment by jjatria** [comment] 2016-01-20 19:17
I cannot reproduce this on my end (Kubuntu 15.10 32-bit running Praat 6.0.11). The executable I'm using was downloaded from the Github releases.

Tab playback works as expected, with both Shift+Tab and plain Tab.

**Comment by drammock** [comment] 2016-01-20 19:29
I just tried the 32-bit version of 6.0.11 and still experience the error.  @jjatria @PaulBoersma any ideas what else I should try to narrow down the cause of this?

**Comment by jjatria** [comment] 2016-01-20 19:37
Is NumLock activated?

**Comment by drammock** [comment] 2016-01-20 19:41
you have got to be joking me.  All this time all I needed was to activate NumLock?  I didn't know it affected any keys outside the number pad.  Worked for me, @Trevortds can you confirm?

**Comment by jjatria** [comment] 2016-01-20 19:48
> all I needed was to activate NumLock?

You had to _activate_ NumLock for Tab to work?

In my computer Tab playback does not work when NumLock is activated.

**Comment by drammock** [comment] 2016-01-20 19:50
**edit** as @jjatria says, it only works if I *deactivate* NumLock.  But I was confused by the fact that apparently the NumLock LED indicator on my keyboard is lit when NumLock is inactive (I rarely use the number pad, so somehow I never noticed before).  So (LEDs notwithstanding) it looks like our computers behave the same way.

**Comment by Trevortds** [comment] 2016-01-20 20:39
Can confirm, the tab key works properly when numlock is off. (my 
keyboard also does not have an indicator light, but I checked the 
behavior with a text editor)

So, I guess this is kind of a workaround. I can live with that. I don't 
do data entry that often, so switching numlock on and off is not a 
problem. Perhaps this quirk should be noted in the documentation, or get 
a spot on the "linux installation" website.

**Comment by PaulBoersma** [comment] 2016-02-04 15:04
I'd like to repair this, but I don't have any keyboards with a numeric keypad. Can anybody look into sys/praat.cpp -> line1449 -> function theKeySnooper, and report to me what event->keyval and event->state become when you press Tab with NumLock on?

**Comment by jjatria** [comment] 2016-02-04 16:54
I tried compiling with `-D_DEBUG`, and uncommenting [these lines](https://github.com/praat/praat/blob/master/external/glpk/colamd.c#L625-L627) from `colamd.c` to no avail.

How can I enable debugging?

**Comment by PaulBoersma** [comment] 2016-02-04 17:37
colamd.c explains that three lines later, but all that isn't really necessary: a simple `printf` in `theKeySnooper` should do fine. Like this:
```
printf ("key event %d %d", (int) event -> keyval, (int) event -> state);
```

**Comment by jjatria** [comment] 2016-02-05 02:36
This is from Praat compiled at 0c065e0 on Kubuntu:

Regular tab

    key event 65289 0
    key event 65289 0

Enable NumLock

    key event 65407 0
    key event 65407 16

Tab with NumLock

    key event 65289 16
    key event 65289 16

Disable NumLock

    key event 65407 16
    key event 65407 16

**Comment by PaulBoersma** [comment] 2016-02-05 10:39
OK, this confirms a remark that I saw somewhere, which is that the NumLock key is associated with the half-named "MOD2" key in GDK. I now know how to fix this (if indeed NumLock is MOD2 on all computers).

**Comment by jjatria** [comment] 2016-02-05 15:59
Good to hear!

I just tried it in a different computer (with an external keyboard) just in case, and the numbers are the same.

**Comment by PaulBoersma** [comment] 2016-02-11 19:10
Can you all check that the problem was fixed in version 6.0.14?

**Comment by jjatria** [comment] 2016-02-11 19:18
Hmmm... no, and in fact 6.0.14 doesn't work for me at all. When I try to play a Sound it plays a sort of garbled sound and crashes. In the console, this is printed when the sound plays:

```
ALSA lib pcm_dmix.c:1024:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib setup.c:548:(add_elem) Cannot obtain info for CTL elem (MIXER,'IEC958 Playback Default',0,0,0): No such file or directory
ALSA lib setup.c:548:(add_elem) Cannot obtain info for CTL elem (MIXER,'IEC958 Playback Default',0,0,0): No such file or directory
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm_dmix.c:1024:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:7905:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7905:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7905:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7905:(snd_pcm_recover) underrun occurred
[... repeated until crash]

```

**Comment by jjatria** [comment] 2016-02-11 19:22
Playing from a script (with `--run`) with 6.0.14 also has the same effect.

**Comment by PaulBoersma** [comment] 2016-02-11 21:24
Please check that it's 6.0.14 (I know you have a 32-bit computer). Did you set the "output sound system" to PulseAudio in "Sound playing preferences"?

**Comment by jjatria** [comment] 2016-02-11 21:48
I just tried again making sure that the Sound playing preferences were set to PulseAudio (which didn't use to work for me), and this time it did work, both with and without NumLock. :)

**Comment by drammock** [comment] 2016-02-12 17:02
confirmed tab key working on Xubuntu 14.04 64-bit (with 64-bit praat 6.0.14), both with and without numlock.  Thanks @PaulBoersma !

**Comment by PaulBoersma** [comment] 2016-02-12 19:16
I'll considered the problem fixed then. Thanks for your help.

**Closed by PaulBoersma** 2016-02-12 19:16 UTC
